import { useEffect, useState } from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  // move to a getstaticprops function?  https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation
    const [listOfProfessors, setProfessors] = useState([]);
    const [listOfCourses, setCourses] = useState([]);

    useEffect(() => {
        (async () => {
            const results = await fetch("/api/listProfs").then(response => response.json());
            setProfessors(results);
        })();
    }, []);

    useEffect(() => {
        (async () => {
            const results = await fetch("/api/listCourses").then(response => response.json());
            setCourses(results);
        })();
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    MongoDB with <a href="https://nextjs.org">Next.js!</a> Example
                </h1>
                <br />
                <div className={styles.grid}>
                    {listOfProfessors.map(professors => (
                        <div className={styles.card} key={professors._id}>
                            <h3>{professors.name}</h3>
                        </div>
                    ))}
                </div>
            </main>
        </div>
    )
}